import type { AuditRule } from "../audit";
import { fail, pass } from "./rule-result";
import { getProjectSourceFiles, getTextLineNumber } from "./source-files";

const STARTER_COPY_PATTERN =
  /Create Next App|Get started by editing\s+(?:app|src\/app)\/page|Welcome to Vite|Vite \+ React|click on the Vite and React logos|Generated by create next app/i;

const noStarterCopyRule: AuditRule = {
  adapters: ["core"],
  category: "production-polish",
  confidence: "high",
  description: "Checks for recognizable framework starter-template copy.",
  id: "no-starter-copy",
  maxScore: 2,
  run: async ({ project }) => {
    const files = await getProjectSourceFiles(project);

    for (const file of files) {
      const line = getTextLineNumber(file.content, STARTER_COPY_PATTERN);

      if (line !== undefined) {
        return fail(
          "Framework starter copy is still visible in application source.",
          "Replace starter-template wording and metadata with product-specific content.",
          {
            filePath: file.path,
            line,
            roast: "The starter template would like its identity back.",
          }
        );
      }
    }

    return pass("No recognizable framework starter copy was found.");
  },
  severity: "info",
  title: "starter copy has been removed",
};

export { noStarterCopyRule };
