const LEGAL_CONTACT_URL = "https://github.com/TheOrcDev/shadscan/issues/new";
const LEGAL_LAST_UPDATED = "July 20, 2026";
const LEGAL_LAST_UPDATED_ISO = "2026-07-20";
const PRIVACY_LAST_UPDATED = "July 21, 2026";
const PRIVACY_LAST_UPDATED_ISO = "2026-07-21";

export {
  LEGAL_CONTACT_URL,
  LEGAL_LAST_UPDATED,
  LEGAL_LAST_UPDATED_ISO,
  PRIVACY_LAST_UPDATED,
  PRIVACY_LAST_UPDATED_ISO,
};
