import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import type { AuditCategory } from "../src/audit";
import { AUDIT_CATEGORIES } from "../src/audit";
import { RULE_CATALOG, type RuleCatalogEntry } from "../src/rule-catalog";
import { BUNDLED_RULESET_VERSION } from "../src/scan";

const OUTPUT_PATH = fileURLToPath(
  new URL("../../../docs/rules.md", import.meta.url)
);

const CATEGORY_TITLES = {
  accessibility: "Accessibility",
  forms: "Forms and Data Entry",
  foundation: "Foundation",
  interaction: "Interaction",
  "production-polish": "Production Polish",
  states: "States",
} as const satisfies Record<AuditCategory, string>;

const escapeTableCell = (value: string): string =>
  value.replaceAll("|", "\\|").replaceAll("\n", " ");

const renderAdapters = (adapters: RuleCatalogEntry["adapters"]): string =>
  adapters.map((adapter) => `\`${adapter}\``).join("<br>");

const renderScoreBehavior = (rule: RuleCatalogEntry): string => {
  if (rule.maxScore === 0 || rule.confidence === "low") {
    return "Advisory";
  }

  const pointLabel = rule.maxScore === 1 ? "point" : "points";
  return `${rule.maxScore} raw ${pointLabel} when applicable`;
};

const renderRuleRow = (rule: RuleCatalogEntry): string =>
  `| \`${rule.id}\` | ${escapeTableCell(rule.description)} | ${rule.confidence} | ${renderScoreBehavior(rule)} | ${renderAdapters(rule.adapters)} |`;

const renderCategory = (category: AuditCategory): string => {
  const rules = RULE_CATALOG.filter((rule) => rule.category === category);

  return [
    `## ${CATEGORY_TITLES[category]} (${rules.length})`,
    "",
    "| Rule | What it checks | Confidence | Score behavior | Adapters |",
    "| --- | --- | --- | --- | --- |",
    ...rules.map(renderRuleRow),
    "",
  ].join("\n");
};

const renderCatalog = (): string =>
  [
    "<!-- Generated by packages/cli/scripts/generate-rule-catalog.ts. Do not edit by hand. -->",
    "# shadscan Rule Catalog",
    "",
    `Bundled ruleset \`${BUNDLED_RULESET_VERSION}\` contains ${RULE_CATALOG.length} deterministic static-analysis rules across ${AUDIT_CATEGORIES.length} categories.`,
    "",
    "Raw rule points are normalized inside each weighted category to produce the 100-point score. Low-confidence failures and zero-point rules are advisories: they appear in the report but do not lower the score.",
    "",
    "Rules only run for matching adapters. A rule can also return `not-applicable` when the relevant UI surface is absent; non-applicable rules are excluded from scoring.",
    "",
    ...AUDIT_CATEGORIES.map(renderCategory),
  ].join("\n");

const main = async (): Promise<void> => {
  const expected = renderCatalog();

  if (process.argv.includes("--check")) {
    const current = await readFile(OUTPUT_PATH, "utf8").catch(() => "");

    if (current !== expected) {
      process.stderr.write(
        "docs/rules.md is stale. Run `pnpm docs:rules` and commit the result.\n"
      );
      process.exitCode = 1;
    }

    return;
  }

  await writeFile(OUTPUT_PATH, expected);
  process.stdout.write(
    `Wrote ${RULE_CATALOG.length} rules to docs/rules.md.\n`
  );
};

await main();
