import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import type { AuditCategory } from "../src/audit";
import { AUDIT_CATEGORIES } from "../src/audit";
import { RULE_CATALOG, type RuleCatalogEntry } from "../src/rule-catalog";
import { BUNDLED_RULESET_VERSION } from "../src/scan";

const DOCS_OUTPUT_PATH = fileURLToPath(
  new URL("../../../docs/rules.md", import.meta.url)
);
const SITE_OUTPUT_PATH = fileURLToPath(
  new URL("../../../lib/generated/rule-catalog.json", import.meta.url)
);

const CATEGORY_TITLES = {
  accessibility: "Accessibility",
  forms: "Forms and Data Entry",
  foundation: "Foundation",
  interaction: "Interaction",
  "production-polish": "Production Polish",
  states: "States",
} as const satisfies Record<AuditCategory, string>;

const escapeTableCell = (value: string): string =>
  value.replaceAll("|", "\\|").replaceAll("\n", " ");

const renderAdapters = (adapters: RuleCatalogEntry["adapters"]): string =>
  adapters.map((adapter) => `\`${adapter}\``).join("<br>");

const renderScoreBehavior = (rule: RuleCatalogEntry): string => {
  if (rule.maxScore === 0 || rule.confidence === "low") {
    return "Advisory";
  }

  const pointLabel = rule.maxScore === 1 ? "point" : "points";
  return `${rule.maxScore} raw ${pointLabel} when applicable`;
};

const renderRuleRow = (rule: RuleCatalogEntry): string =>
  `| \`${rule.id}\` | ${escapeTableCell(rule.description)} | ${rule.confidence} | ${renderScoreBehavior(rule)} | ${renderAdapters(rule.adapters)} |`;

const renderCategory = (category: AuditCategory): string => {
  const rules = RULE_CATALOG.filter((rule) => rule.category === category);

  return [
    `## ${CATEGORY_TITLES[category]} (${rules.length})`,
    "",
    "| Rule | What it checks | Confidence | Score behavior | Adapters |",
    "| --- | --- | --- | --- | --- |",
    ...rules.map(renderRuleRow),
    "",
  ].join("\n");
};

const renderCatalog = (): string =>
  [
    "<!-- Generated by packages/cli/scripts/generate-rule-catalog.ts. Do not edit by hand. -->",
    "# shadscan Rule Catalog",
    "",
    `Bundled ruleset \`${BUNDLED_RULESET_VERSION}\` contains ${RULE_CATALOG.length} deterministic static-analysis rules across ${AUDIT_CATEGORIES.length} categories.`,
    "",
    "Raw rule points are normalized inside each weighted category to produce the 100-point score. Low-confidence failures and zero-point rules are advisories: they appear in the report but do not lower the score.",
    "",
    "Rules only run for matching adapters. A rule can also return `not-applicable` when the relevant UI surface is absent; non-applicable rules are excluded from scoring.",
    "",
    ...AUDIT_CATEGORIES.map(renderCategory),
  ].join("\n");

const renderSiteCatalog = (): string => {
  const categories = AUDIT_CATEGORIES.map((id) => ({
    id,
    title: CATEGORY_TITLES[id],
  }));

  return `${JSON.stringify(
    {
      categories,
      rules: RULE_CATALOG,
      rulesetVersion: BUNDLED_RULESET_VERSION,
    },
    null,
    2
  )}\n`;
};

const main = async (): Promise<void> => {
  const expectedDocs = renderCatalog();
  const expectedSiteCatalog = renderSiteCatalog();

  if (process.argv.includes("--check")) {
    const [currentDocs, currentSiteCatalog] = await Promise.all([
      readFile(DOCS_OUTPUT_PATH, "utf8").catch(() => ""),
      readFile(SITE_OUTPUT_PATH, "utf8").catch(() => ""),
    ]);
    const staleOutputs = [
      currentDocs === expectedDocs ? null : "docs/rules.md",
      currentSiteCatalog === expectedSiteCatalog
        ? null
        : "lib/generated/rule-catalog.json",
    ].filter((output): output is string => output !== null);

    if (staleOutputs.length > 0) {
      process.stderr.write(
        `${staleOutputs.join(", ")} ${staleOutputs.length === 1 ? "is" : "are"} stale. Run \`pnpm docs:rules\` and commit the result.\n`
      );
      process.exitCode = 1;
    }

    return;
  }

  await mkdir(dirname(SITE_OUTPUT_PATH), { recursive: true });
  await Promise.all([
    writeFile(DOCS_OUTPUT_PATH, expectedDocs),
    writeFile(SITE_OUTPUT_PATH, expectedSiteCatalog),
  ]);
  process.stdout.write(
    `Wrote ${RULE_CATALOG.length} rules to docs/rules.md and lib/generated/rule-catalog.json.\n`
  );
};

await main();
